### ISSUE TITLE
Add support for waveforms of strings

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [DiamondLightSource/epics_device#7]
It is possible to create a waveform with an FTVL of "STRING", thus allowing a waveform where each element is a 40-character string as per standard EPICS convention.

```
record(waveform, "$(DEVICE):MAGNET_NAMES")
{
    field(FTVL, "STRING")
    field(INP,  "@MAGNET_NAMES")
    field(NELM, "4")
}
```

Currently it is not possible to make one of these using `epics_device`. There is no `waveform_type` enum value for it (although there is already `EPICS_STRING` typedef).

The fix may be as simple as adding the relevant enum value?

**Comment by Araneidae** [comment]
Fixed in commit 75e2de15d423e81be2c4640ae6093dbb2cd73473
